import type { CombatAbility, EnemyWithLoadout } from "./combatAdminService";
import type { MapEvent, MapMarker } from "./mapService";
import type { ArenaWithLeaders } from "./arenaService";
import type { PlayerBattleSnapshot } from "./battleSnapshotService";

export function createArenaChallengeEvent(marker: MapMarker, arena: ArenaWithLeaders, defender: PlayerBattleSnapshot): MapEvent {
  const now = new Date().toISOString();

  return {
    id: marker.id,
    event_type: "battle",
    title: `${arena.arena?.name || marker.title} Challenge`,
    route_id: null,
    distance_marker_percent: 0,
    background_image_url: arena.arena?.background_image_url ?? marker.scene_background_image_url ?? null,
    npc_name: null,
    npc_portrait_url: null,
    dialogue_npc_id: null,
    npc_id: null,
    dialogue_text: null,
    choices: [],
    enemy_name: defender.character_name,
    enemy_id: null,
    enemy_image_url: defender.portrait_url,
    enemy_hp: Math.max(1, Number(defender.max_health) || 30),
    enemy_attack_damage: Math.max(1, Number(defender.damage_bonus) + Number(defender.attack_bonus) || 4),
    battle_intro_text: `${defender.character_name} is defending this arena. Party members cannot join arena challenges.`,
    victory_text: `You defeated ${defender.character_name}.`,
    defeat_text: `${defender.character_name} holds the arena.`,
    reward_xp: Math.max(0, Number(arena.arena?.reward_xp ?? marker.reward_xp ?? 0) || 0),
    reward_gold: Math.max(0, Number(arena.arena?.reward_gold ?? marker.reward_gold ?? 0) || 0),
    reward_item: null,
    reward_item_id: null,
    reward_item_quantity: 1,
    trigger_mode: "fixed",
    random_chance_percent: 0,
    linked_only: true,
    season_number: Number(marker.season_number ?? arena.arena?.season_number ?? 1) || 1,
    chapter_number: Number(marker.chapter_number ?? arena.arena?.chapter_number ?? 1) || 1,
    is_active: true,
    created_by: marker.created_by,
    created_at: now,
    updated_at: now,
  };
}

export function createArenaSnapshotOpponent(snapshot: PlayerBattleSnapshot): EnemyWithLoadout {
  const attributes = snapshot.attributes ?? {};
  const abilities = Array.isArray(snapshot.equipped_abilities) ? snapshot.equipped_abilities : [];
  const syntheticAbilities = abilities.map((ability, index) => ({
    id: `arena-${snapshot.id}-${index}`,
    enemy_id: snapshot.id,
    ability_id: String(ability.id ?? `arena-ability-${index}`),
    use_weight: Math.max(1, Number(ability.useWeight ?? 1) || 1),
    created_at: snapshot.created_at,
    updated_at: snapshot.updated_at,
    ability: {
      id: String(ability.id ?? `arena-ability-${index}`),
      name: String(ability.name ?? "Strike"),
      type: String(ability.type ?? "attack") as CombatAbility["type"],
      damage: Math.max(0, Number(ability.damage ?? 0) || 0),
      healing: Math.max(0, Number(ability.healing ?? 0) || 0),
      defense_amount: Math.max(0, Number(ability.defenseAmount ?? 0) || 0),
      stamina_restore: Math.max(0, Number(ability.staminaRestore ?? 0) || 0),
      magika_restore: Math.max(0, Number(ability.magikaRestore ?? 0) || 0),
      stamina_cost: Math.max(0, Number(ability.staminaCost ?? 0) || 0),
      magika_cost: Math.max(0, Number(ability.magikaCost ?? 0) || 0),
      health_cost: Math.max(0, Number(ability.healthCost ?? 0) || 0),
      hit_chance: 75,
      critical_chance: Math.max(0, Number(ability.criticalChance ?? 5) || 0),
      critical_multiplier: Math.max(1, Number(ability.criticalMultiplier ?? 2) || 2),
      cooldown_turns: 0,
      duration_turns: 0,
      status_effect: String(ability.statusEffect ?? "none") as CombatAbility["status_effect"],
      effect_amount: Math.max(0, Number(ability.effectAmount ?? 0) || 0),
      effect_duration: Math.max(0, Number(ability.effectDuration ?? 0) || 0),
      linked_stat: String(ability.attribute ?? "strength") as CombatAbility["linked_stat"],
      learn_method: "admin" as CombatAbility["learn_method"],
      required_level: 0,
      required_attribute: String(ability.attribute ?? "strength") as CombatAbility["required_attribute"],
      required_attribute_level: 0,
      required_class_key: null,
      image_path: typeof ability.imagePath === "string" ? ability.imagePath : null,
      usage_context: "battle_only" as CombatAbility["usage_context"],
      attack_bonus: Math.max(0, Number(ability.attackBonus ?? 0) || 0),
      season_number: 1,
      chapter_number: 1,
      is_active: true,
      created_by: null,
      created_at: snapshot.created_at,
      updated_at: snapshot.updated_at,
    },
  }));

  return {
    id: snapshot.id,
    name: snapshot.character_name,
    type: snapshot.active_class_key || "Arena Holder",
    image_url: snapshot.portrait_url,
    health: Math.max(1, Number(snapshot.max_health) || 30),
    stamina: Math.max(0, Number(snapshot.max_stamina) || 0),
    magika: Math.max(0, Number(snapshot.max_magika) || 0),
    strength: Number(attributes.strength ?? 0) || 0,
    endurance: Number(attributes.endurance ?? 0) || 0,
    agility: Number(attributes.agility ?? 0) || 0,
    intelligence: Number(attributes.intelligence ?? 0) || 0,
    wisdom: Number(attributes.wisdom ?? 0) || 0,
    charisma: Number(attributes.charisma ?? 0) || 0,
    spirit: Number(attributes.spirit ?? 0) || 0,
    defense: Math.max(10, Number(snapshot.defense) || 10),
    attack_bonus: Math.max(0, Number(snapshot.attack_bonus) || 0),
    armor_rating: 0,
    xp_reward: 0,
    gold_reward: 0,
    season_number: 1,
    chapter_number: 1,
    is_active: true,
    created_by: null,
    created_at: snapshot.created_at,
    updated_at: snapshot.updated_at,
    abilities: syntheticAbilities as EnemyWithLoadout["abilities"],
    drops: [],
  };
}
