insert into public.npc_definitions (
  id,
  name,
  type,
  description,
  image_url,
  can_battle,
  health,
  stamina,
  magika,
  strength,
  endurance,
  agility,
  intelligence,
  wisdom,
  charisma,
  spirit,
  defense,
  armor_rating,
  xp_reward,
  gold_reward,
  attack_bonus,
  season_number,
  chapter_number,
  is_active,
  created_by,
  created_at,
  updated_at
)
values
  (
    '5be38cf0-473d-5ae4-8fb6-fbe545cd7cc2',
    'Aldric Stonebrook',
    'Raven''s Rest Town Folk',
    'A weathered fisherman who has worked the river outside Raven''s Rest for most of his life. Quiet, observant, and slow to trust rumors.',
    null,
    false,
    20,
    10,
    0,
    1,
    2,
    1,
    1,
    3,
    1,
    2,
    10,
    0,
    0,
    0,
    2,
    1,
    1,
    true,
    null,
    now(),
    now()
  ),
  (
    '1b758c44-6441-59df-b69b-8d813dad69e1',
    'Clara Fenwood',
    'Raven''s Rest Town Folk',
    'A hardworking village woman who keeps busy helping neighbors while the town waits for news of the missing princess.',
    null,
    false,
    20,
    10,
    0,
    1,
    2,
    1,
    1,
    2,
    2,
    2,
    10,
    0,
    0,
    0,
    2,
    1,
    1,
    true,
    null,
    now(),
    now()
  ),
  (
    '3fae8dcd-ce9f-5216-aef3-f741710b7079',
    'Edith Holloway',
    'Raven''s Rest Town Folk',
    'An elderly resident of Raven''s Rest known for her kindness, sharp memory, and steady faith during difficult times.',
    null,
    false,
    18,
    8,
    0,
    0,
    1,
    0,
    2,
    4,
    2,
    4,
    10,
    0,
    0,
    0,
    2,
    1,
    1,
    true,
    null,
    now(),
    now()
  ),
  (
    '6b3beb34-ff68-5474-995f-197b001e92f8',
    'Jeb Crowe',
    'Raven''s Rest Town Folk',
    'The town drunk and a familiar face at the inn. Most dismiss his rambling, though he notices more than people realize.',
    null,
    false,
    20,
    8,
    0,
    1,
    1,
    0,
    1,
    2,
    1,
    1,
    10,
    0,
    0,
    0,
    2,
    1,
    1,
    true,
    null,
    now(),
    now()
  ),
  (
    '9c46e4c1-691f-5ab6-9b53-99fa686302ae',
    'Owen Barrett',
    'Raven''s Rest Town Folk',
    'A friendly tavern regular who knows the rhythms of the town and keeps track of every rumor passing through the inn.',
    null,
    false,
    22,
    10,
    0,
    2,
    2,
    1,
    1,
    2,
    3,
    1,
    10,
    0,
    0,
    0,
    2,
    1,
    1,
    true,
    null,
    now(),
    now()
  )
on conflict (id) do update
set
  name = excluded.name,
  type = excluded.type,
  description = excluded.description,
  image_url = excluded.image_url,
  can_battle = excluded.can_battle,
  health = excluded.health,
  stamina = excluded.stamina,
  magika = excluded.magika,
  strength = excluded.strength,
  endurance = excluded.endurance,
  agility = excluded.agility,
  intelligence = excluded.intelligence,
  wisdom = excluded.wisdom,
  charisma = excluded.charisma,
  spirit = excluded.spirit,
  defense = excluded.defense,
  armor_rating = excluded.armor_rating,
  xp_reward = excluded.xp_reward,
  gold_reward = excluded.gold_reward,
  attack_bonus = excluded.attack_bonus,
  season_number = excluded.season_number,
  chapter_number = excluded.chapter_number,
  is_active = excluded.is_active,
  updated_at = now();
